### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by AndrewJGregory** [AndrewJGregory/Procify#1]

**Comment by mashuDuek** [comment]
Landing page: 
1. Buttons to signup and login are too small. 
2. Font for the two above buttons is too big. 
3. The written part on the write and the buttons on the left must be separated with a border - check spotify. 
4. The text between the buttons needs to be more similar to the spotify one. 
5. The text on the right needs to be spaced more adequately and also try and find a more similar font. 

Login/Signup pages: 
1. The border separating the "logo" and the input fields is too thick. 
2. The input fields are too long and not tall enough. 
3. The button to signup is not wide enough and the text is too large. 
--- similar issues for the login page.

**Comment by mashuDuek** [comment]
1. The line separating the buttons (signup and login) and the text on the right needs to be thinner. 
2. The placeholders in the signup form need to be bigger
3. The input fields needs to have a border radius 
4. The button to signup needs to be the same width as the form 
5. The signup form needs to have two email input fields (and obviously make sure that the second one matches the first)
6. They also have a "What should we call you?" (I guess username?) field
7. The color of your error handling needs to be a darker red I believe (I'm colorblind, hopefully not wrong) 
8. The "Already have an account? Log in" text needs to be more bubbly. I don't need it to be exact font, but more similar for sure
9. Most of the above goes the same for the login form - except the button, button goes on the right hand side of the form (so its good as is)

**Comment by mashuDuek** [comment]
1. So apparently I can be born in the future

**Comment by mashuDuek** [comment]
Awesome job! Close it. Sorry for not being present in answering directly to other features (issues opened) - we've been out of a few TA's the entire full-stacks, including myself a couple days, due to sickness. Your doing a super awesome job!
